### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by zhangbaijin** [wangguanzhi/LADN#6]
Hi,guanzhi,there is a problem occured.
`--- load model ---
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
start the training at epoch 2800

--- train ---
starting forward for testing images
Traceback (most recent call last):
  File "run.py", line 152, in <module>
    main()
  File "run.py", line 85, in main
    model.test_forward(images_a, images_b, images_c)
  File "/opt_ext_one/Documents/sfj/LADN/src/model.py", line 763, in test_forward
    self.z_content_a, self.z_content_b = self.enc_c.forward(self.real_A_encoded, self.real_B_encoded)
  File "/opt_ext_one/Documents/sfj/LADN/src/networks.py", line 140, in forward
    outputA = self.forward_a(xa)
  File "/opt_ext_one/Documents/sfj/LADN/src/networks.py", line 148, in forward_a
    e1_2_A = self.bn_e1_A(self.conv2_e1_A(self.relu_e1_A(e1_1_A)))
  File "/home/peter/miniconda3/envs/TF_and_Pytorch_GPU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/peter/miniconda3/envs/TF_and_Pytorch_GPU/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/home/peter/miniconda3/envs/TF_and_Pytorch_GPU/lib/python3.6/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM`
Thanks for your time!

**Comment by DanielMao2015** [comment]
the batch_size should not set to 1.
